packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*
  - docs
  - playground
catalog:
  '@changesets/cli': ^2.27.9
  '@changesets/git': ^3.0.1
  '@eslint/js': ^9.15.0
  '@manypkg/get-packages': ^2.2.2
  '@types/node': ^22.9.0
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.14.0
  '@typescript-eslint/parser': ^8.14.0
  cac: ^6.7.14
  chalk: ^5.3.0
  circular-dependency-scanner: ^2.3.0
  consola: ^3.2.3
  dayjs: ^1.11.13
  depcheck: ^1.4.7
  eslint: ^9.15.0
  eslint-config-turbo: ^2.3.0
  eslint-plugin-command: ^0.2.6
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.4.2
  eslint-plugin-jsdoc: ^50.5.0
  eslint-plugin-jsonc: ^2.18.1
  eslint-plugin-n: ^17.13.2
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.31.0
  execa: ^9.5.1
  find-up: ^7.0.0
  globals: ^15.12.0
  jsonc-eslint-parser: ^2.4.0
  ora: ^8.1.1
  pkg-types: ^1.2.1
  prettier: ^3.3.3
  publint: ^0.2.12
  rimraf: ^6.0.1
  rollup: ^4.27.2
  unbuild: ^3.0.0-rc.11
  turbo: ^2.3.0
  typescript: ^5.6.3
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.4.5
  vite: ^5.4.11
