packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*
  - docs
  - playground
catalog:
  '@changesets/cli': ^2.27.9
  '@eslint/js': ^9.15.0
  '@types/eslint': ^9.6.1
  '@types/node': ^22.9.0
  '@typescript-eslint/eslint-plugin': ^8.14.0
  '@typescript-eslint/parser': ^8.14.0
  eslint: ^9.15.0
  eslint-config-turbo: ^2.3.0
  prettier: ^3.3.3
  rimraf: ^6.0.1
  rollup: ^4.27.2
  turbo: ^2.3.0
  typescript: ^5.6.3
  unbuild: ^3.0.0-rc.11
  unplugin-element-plus: ^0.8.0
  vite: ^5.4.11
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: 4.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^0.21.0
  vite-plugin-vue-devtools: ^7.6.4
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-i18n: ^10.0.4
  vue-router: ^4.4.5
  vue-tsc: ^2.1.10
