name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Type Check
        run: pnpm run check:type

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run Tests
        run: pnpm run test
        env:
          CI: true
